import * as fs from 'fs';
import * as path from 'path';
import { google } from '@ai-sdk/google';
import { generateObject } from 'ai';
import { z } from 'zod';
import * as dotenv from 'dotenv';
import { parse } from 'csv-parse/sync';

dotenv.config({ path: '.env.local' });

const dataDir = path.join(process.cwd(), 'data');

interface ProposedMatch {
  bank_id: string;
  ledger_ids: string[];
  confidence: number;
  reason: string;
}

async function runCheckerAgent() {
  console.log("Loading datasets and Maker proposals for audit...");
  
  const makerProposals: ProposedMatch[] = JSON.parse(
    fs.readFileSync(path.join(dataDir, 'maker_proposals.json'), 'utf-8')
  );
  
  const ledgerCsv = fs.readFileSync(path.join(dataDir, 'internal_ledger.csv'), 'utf-8');
  const bankCsv = fs.readFileSync(path.join(dataDir, 'bank_statement.csv'), 'utf-8');

  const ledgers = parse(ledgerCsv, { columns: true, skip_empty_lines: true });
  const banks = parse(bankCsv, { columns: true, skip_empty_lines: true });

  const ledgerMap = new Map(ledgers.map((l: any) => [l.internal_txn_id, l]));
  const bankMap = new Map(banks.map((b: any) => [b.bank_stmt_id, b]));

  const auditPackages = makerProposals.map(proposal => {
    const bankRecord = bankMap.get(proposal.bank_id);
    const matchedLedgers = proposal.ledger_ids.map(id => ledgerMap.get(id)).filter(Boolean);
    return {
      proposal,
      bankRecord,
      matchedLedgers
    };
  });

  console.log(`Auditing ${auditPackages.length} proposals with zero-temperature Checker Agent...`);

  const { object } = await generateObject({
    model: google('gemini-2.5-flash'),
    temperature: 0.0, 
    system: `You are a strict, skeptical Senior Financial Auditor (Checker Agent) for Razorpay.
    Your sole task is to independently verify reconciliation proposals generated by the Maker Agent.

    Verification Rules:
    1. Mathematical Verification:
       - Calculate the exact sum of all matched ledger amounts.
       - Compare this sum to the bank record's credit_amount.
       - An exact match is APPROVED.
       - A difference matching an exact 2% MDR deduction (bank_amount ≈ ledger_amount * 0.98) is APPROVED.
       - Any unexplained discrepancy must be REJECTED.
    2. Date Verification:
       - Bank settlement (val_date) must be within 0 to 4 days after the ledger transaction created_at date.
    3. Collision Detection:
       - No ledger transaction should appear in multiple matches.

    For every proposal, issue a verdict:
    - "APPROVED": Fully verified against all invariants.
    - "REJECTED": Invariants violated.
    - "FLAGGED_FOR_HUMAN": Borderline cases or unusual narration ambiguity.`,
    prompt: `Audit the following reconciliation proposals against their raw bank and ledger data:\n${JSON.stringify(auditPackages, null, 2)}`,
    schema: z.object({
      audit_results: z.array(
        z.object({
          bank_id: z.string(),
          ledger_ids: z.array(z.string()),
          verdict: z.enum(['APPROVED', 'REJECTED', 'FLAGGED_FOR_HUMAN']),
          math_verification: z.object({
            total_ledger_amount: z.number(),
            bank_credit_amount: z.number(),
            difference: z.number(),
            is_valid_fee_tolerance: z.boolean()
          }),
          audit_explanation: z.string().describe("Concise explanation of the verdict")
        })
      )
    })
  });

  fs.writeFileSync(path.join(dataDir, 'checker_audit_log.json'), JSON.stringify(object.audit_results, null, 2));

  const approved = object.audit_results.filter(r => r.verdict === 'APPROVED').length;
  const rejected = object.audit_results.filter(r => r.verdict === 'REJECTED').length;
  const flagged = object.audit_results.filter(r => r.verdict === 'FLAGGED_FOR_HUMAN').length;

  console.log("\n=== Checker Agent Audit Complete ===");
  console.log(`Total Proposals Audited: ${object.audit_results.length}`);
  console.log(`✅ Approved: ${approved}`);
  console.log(`❌ Rejected: ${rejected}`);
  console.log(`⚠️ Flagged for Human: ${flagged}`);
  console.log("Audit log saved to data/checker_audit_log.json");
}

runCheckerAgent().catch(console.error);